name: Deploy App
on:
    push:
      branches:
        - master
        - 'releases/**'
      paths-ignore:
        - 'docs/**'

env:
  REMOTE_HOST: 'doron.perdiemmembership.com'
  USERNAME: 'devop'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
            node-version: '16.x'
      - run: npm install
      - run: npm run build --if-present